### ISSUE TITLE
URLs to hyperlinks in Smilee chat?

### ISSUE THREAD

**Issue by hannu78** [smileeio/smileeio.github.io#1]
Would it be feasible that URL's in chat discussion would be shown as hyperlinks that open in new browser tab/window? Currently they need to be copy-pasted from chat to access.

**Comment by jlumme** [comment]
Currently links that are part of the domain context of the chat window are shown as hyperlinks, links to other sites are not. You can add the link domain to be part of the domain but I'll also bring this issue up in our next meeting if we could change to behaviour of links in chat

**Comment by hannu78** [comment]
ok. We would like to have all links as hyperlinks as customers use several domains with our produts as well.

**Comment by jlumme** [comment]
We have now included flag `acceptAllUrls`, with this you can tell the enduser client to render all links as clickable links.
