### ISSUE TITLE
Agent name to be visible in chatlog e-mails

### ISSUE THREAD

**Issue by hannu78** [smileeio/smileeio.github.io#3]
Hi! Currently chatlog sent in e-mail reads on "Agent" instead of agent's name in chatlogs. Could the name be visible there, it would really help us if we need to check the chatlogs while supporting the customer further later on and we could see who has been chatting with the customer before.

**Comment by jlumme** [comment]
Tonight we'll make a release where this issue is fixed. Release also allows setting a contact-form email to the team from admintool settings
